hadoop distcp s3n://p41-dataset/wiki-dataset/part00.txt.gz /task1/totalInput/
hadoop distcp s3n://p41-dataset/wiki-dataset/part01.txt.gz /task1/totalInput/
hadoop distcp s3n://p41-dataset/wiki-dataset/part02.txt.gz /task1/totalInput/
hadoop distcp s3n://p41-dataset/wiki-dataset/part03.txt.gz /task1/totalInput/
hadoop distcp s3n://p41-dataset/wiki-dataset/part04.txt.gz /task1/totalInput/
hadoop distcp s3n://p41-dataset/wiki-dataset/part05.txt.gz /task1/totalInput/
hadoop distcp s3n://p41-dataset/wiki-dataset/part06.txt.gz /task1/totalInput/
hadoop distcp s3n://p41-dataset/wiki-dataset/part07.txt.gz /task1/totalInput/
hadoop distcp s3n://p41-dataset/wiki-dataset/part08.txt.gz /task1/totalInput/
hadoop distcp s3n://p41-dataset/wiki-dataset/part09.txt.gz /task1/totalInput/
hadoop distcp s3n://p41-dataset/wiki-dataset/part10.txt.gz /task1/totalInput/
hadoop distcp s3n://p41-dataset/wiki-dataset/part11.txt.gz /task1/totalInput/
hadoop distcp s3n://p41-dataset/wiki-dataset/part12.txt.gz /task1/totalInput/
hadoop distcp s3n://p41-dataset/wiki-dataset/part13.txt.gz /task1/totalInput/
hadoop distcp s3n://p41-dataset/wiki-dataset/part14.txt.gz /task1/totalInput/
hadoop distcp s3n://p41-dataset/wiki-dataset/part15.txt.gz /task1/totalInput/
hadoop distcp s3n://p41-dataset/wiki-dataset/part16.txt.gz /task1/totalInput/
hadoop distcp s3n://p41-dataset/wiki-dataset/part17.txt.gz /task1/totalInput/
hadoop distcp s3n://p41-dataset/wiki-dataset/part18.txt.gz /task1/totalInput/
hadoop distcp s3n://p41-dataset/wiki-dataset/part19.txt.gz /task1/totalInput/
hadoop distcp s3n://p41-dataset/wiki-dataset/part20.txt.gz /task1/totalInput/
hadoop distcp s3n://p41-dataset/wiki-dataset/part21.txt.gz /task1/totalInput/
hadoop distcp s3n://p41-dataset/wiki-dataset/part22.txt.gz /task1/totalInput/
hadoop distcp s3n://p41-dataset/wiki-dataset/part23.txt.gz /task1/totalInput/
hadoop distcp s3n://p41-dataset/wiki-dataset/part24.txt.gz /task1/totalInput/
hadoop distcp s3n://p41-dataset/wiki-dataset/part25.txt.gz /task1/totalInput/
hadoop distcp s3n://p41-dataset/wiki-dataset/part26.txt.gz /task1/totalInput/
hadoop distcp s3n://p41-dataset/wiki-dataset/part27.txt.gz /task1/totalInput/
hadoop distcp s3n://p41-dataset/wiki-dataset/part28.txt.gz /task1/totalInput/
hadoop distcp s3n://p41-dataset/wiki-dataset/part29.txt.gz /task1/totalInput/
hadoop distcp s3n://p41-dataset/wiki-dataset/part30.txt.gz /task1/totalInput/
hadoop distcp s3n://p41-dataset/wiki-dataset/part31.txt.gz /task1/totalInput/
hadoop distcp s3n://p41-dataset/wiki-dataset/part32.txt.gz /task1/totalInput/
hadoop distcp s3n://p41-dataset/wiki-dataset/part33.txt.gz /task1/totalInput/
hadoop distcp s3n://p41-dataset/wiki-dataset/part34.txt.gz /task1/totalInput/
hadoop distcp s3n://p41-dataset/wiki-dataset/part35.txt.gz /task1/totalInput/
hadoop distcp s3n://p41-dataset/wiki-dataset/part36.txt.gz /task1/totalInput/
hadoop distcp s3n://p41-dataset/wiki-dataset/part37.txt.gz /task1/totalInput/
hadoop distcp s3n://p41-dataset/wiki-dataset/part38.txt.gz /task1/totalInput/
hadoop distcp s3n://p41-dataset/wiki-dataset/part39.txt.gz /task1/totalInput/
hadoop distcp s3n://p41-dataset/wiki-dataset/part40.txt.gz /task1/totalInput/
hadoop distcp s3n://p41-dataset/wiki-dataset/part41.txt.gz /task1/totalInput/
hadoop distcp s3n://p41-dataset/wiki-dataset/part42.txt.gz /task1/totalInput/
hadoop distcp s3n://p41-dataset/wiki-dataset/part43.txt.gz /task1/totalInput/
hadoop distcp s3n://p41-dataset/wiki-dataset/part44.txt.gz /task1/totalInput/
hadoop distcp s3n://p41-dataset/wiki-dataset/part45.txt.gz /task1/totalInput/
hadoop distcp s3n://p41-dataset/wiki-dataset/part46.txt.gz /task1/totalInput/
hadoop distcp s3n://p41-dataset/wiki-dataset/part47.txt.gz /task1/totalInput/
hadoop distcp s3n://p41-dataset/wiki-dataset/part48.txt.gz /task1/totalInput/
hadoop distcp s3n://p41-dataset/wiki-dataset/part49.txt.gz /task1/totalInput/
hadoop distcp s3n://p41-dataset/wiki-dataset/part50.txt.gz /task1/totalInput/
hadoop distcp s3n://p41-dataset/wiki-dataset/part51.txt.gz /task1/totalInput/
hadoop distcp s3n://p41-dataset/wiki-dataset/part52.txt.gz /task1/totalInput/
hadoop distcp s3n://p41-dataset/wiki-dataset/part53.txt.gz /task1/totalInput/
hadoop distcp s3n://p41-dataset/wiki-dataset/part54.txt.gz /task1/totalInput/
hadoop distcp s3n://p41-dataset/wiki-dataset/part55.txt.gz /task1/totalInput/
hadoop distcp s3n://p41-dataset/wiki-dataset/part56.txt.gz /task1/totalInput/
hadoop distcp s3n://p41-dataset/wiki-dataset/part57.txt.gz /task1/totalInput/
hadoop distcp s3n://p41-dataset/wiki-dataset/part58.txt.gz /task1/totalInput/
hadoop distcp s3n://p41-dataset/wiki-dataset/part59.txt.gz /task1/totalInput/
hadoop distcp s3n://p41-dataset/wiki-dataset/part60.txt.gz /task1/totalInput/
hadoop distcp s3n://p41-dataset/wiki-dataset/part61.txt.gz /task1/totalInput/
hadoop distcp s3n://p41-dataset/wiki-dataset/part62.txt.gz /task1/totalInput/
hadoop distcp s3n://p41-dataset/wiki-dataset/part63.txt.gz /task1/totalInput/
